language: node_js
node_js:
  - "13"

addons:
  ssh_known_hosts: mira.littledev.nl

env:
  global:
    - FTP_HOST: littledev.nl
    # FTP_USER
    - secure: BzHNCTgHZ6ezvhj40web2eFa/BJQPDZDGmPjxJAoK0HrNAs5bLRwBh5b38HIF3MGO26eUifLtiEzvLdBRMkCgX/3Ntfp3NvbJqMMayDn4pL4cR2CXh2waOE30eJ/H8HP6QAC/grJIg+iDrA7/GysvyqnmVsBdhH0y388mCrJ0wu5gCJqOX2sKxFFAOjAorzd2XArjYDPQDmgFJQu1ZSEIoSJwF2wRaTh9s+PTI1AOOEIAOefPwG8uI6RAtVFkRofXxlrkZkrk3p0lO2Oer014uI69tNJT0656R9ykTcGIeBPYR7YEDBap9jsLuWcaGtHBFT1r0Gco28jiqjgBsCiWv1t7MKJb9HbZtOoBwoV3t8ubFVyRUvoFkro3r/znOvd2tu2j2922cBpZyLqbaP43xE4Cc3KBdf9Q1EHhC3VmRQike6X8MzG4/tfZ5Pvy0z8tUfL+ZcGb2SB1SZzbg+fygd09WV5gJEeVgtFzrx2m2Hy1TR5UzKidaGiWMcueWEN0WIi5ZWjxr7ue1OI1QITYBJyTKdaJk0BR5E40JJ1qaujfu7DcgVHEpH6Q8ZAa2S0YNpUqAzp3FTk7X35aUCXzN9KMjmq9TEkad+CNToXfvsm+R4STRdeqziYdA1Fet1ZN0hll0ZS1a14WfYwDO3vbbsSIuT6jg3ZUeiBf9oyP+U=
    # FTP_PASS
    - secure: STrpAJrObCcZPrwpnqEMl4xB2ccz8ejRfKa0hebCPN53OMOkawOQi0Qxx0GW0MP45JY845h5lLPRk3UIApbQSurcut36Jih7fuk9vHuVDtjwRWZze4Iif7/k9ZYtZFS+hn+IZyNpyGlsa11XPvwgJM4l71wgWvHmSGZN4C1nQ/ZIn3xsNjYe8qROrC59a2zT+onYp2OYTdNaLEVu+C12TGknPc19cODbeXsoCs5WbBfMDgfN585whK2jG9/2Pgf2vLCI59+q1s0TC8X0lWDxFCSo0oN/RmHqZ3rogw/cQvOu/40PHK7dd7KWWIefcv5eYcU7qXNi+1kcemqM/S/+h03/Em8LXBzlXxrYroP8NkpMaJ+R7clRNx0Ze+II+jkpQRUGM6yEydiGdJNc05vUXVgPSlX9mCUKQRjZgOPLsHVjoAGim7FtLkV6adrH9apbdNcNMHRzTeKbobXfdGWF733WkryG3pq3ZzXiePmRjSu5MZZymTQgPgb+c7CZLpzVIEdlmnvy/2imssfrImph/LHng8nNz1dwjoBkEYaB3Vu9GvM00RNlk/PNrhymyqqabj9aO1glL7H7dUoCBznQyhTj//0iRdgZDoRAVkNWAl1wrd6845XelDtEvcjs10NEWOjBTu2inbB+uLSR8D11E2QqraqsnDBM+/qqIli9acU=

before_script:
  - npm install -g @angular/cli
  - npm install -g pm2
  - cd divingapp
  - yarn

script:
  - ng build --prod --base-href https://dive.littledev.nl/

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_7e0ade2cd31e_key -iv $encrypted_7e0ade2cd31e_iv
    -in mira_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - npm install -g gulp-cli
  - cd travis-ftp
  - yarn
  - cd $TRAVIS_BUILD_DIR
  - chmod a+x deploy_prod.sh

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy_prod.sh"
  on:
    branch: master

cache:
  directories:
    - divingapp/node_modules

notifications:
  email:
    - vinnie@script4web.nl
