language: node_js
node_js:
  - "13"

addons:
  ssh_known_hosts:
    - mira.littledev.nl
    - littledev.nl

before_script:
  - npm install -g @angular/cli
  - cd divingapp
  - yarn

script:
  - ng build --prod --base-href https://dive.littledev.nl/

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_7e0ade2cd31e_key -iv $encrypted_7e0ade2cd31e_iv
    -in mira_rsa.enc -out /tmp/deploy_rsa -d
  - openssl aes-256-cbc -K $encrypted_ed605b757ff8_key -iv $encrypted_ed605b757ff8_iv
    -in ftp_rsa.enc -out /tmp/ftp_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - chmod 600 /tmp/ftp_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-add /tmp/ftp_rsa
  - cd $TRAVIS_BUILD_DIR
  - chmod a+x deploy_prod.sh

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy_prod.sh"
  on:
    branch: master

cache:
  directories:
    - divingapp/node_modules

notifications:
  email:
    - vinnie@script4web.nl
