language: node_js
node_js:
  - "13"

services:
  - docker

env:
  global:
    - DOCKER_REPO=littledivelogserver

addons:
  chrome: stable
  ssh_known_hosts:
    - mira.littledev.nl
    - littledev.nl

stages:
  - test
  - name: deploy
    if: (branch = master) AND (type = push)

before_install:
  - yarn global add @angular/cli
  - yarn global add jake

install:
  - cd $TRAVIS_BUILD_DIR/divingapp
  - yarn
  - cd $TRAVIS_BUILD_DIR/divingserver
  - yarn

jobs:
  include:
    - stage: test
      script:
        - cd $TRAVIS_BUILD_DIR/divingapp
        - yarn run test-headless
    - stage: deploy
      script:
        - cd $TRAVIS_BUILD_DIR/divingapp
        - ng build --prod --base-href https://dive.littledev.nl/
        - cd $TRAVIS_BUILD_DIR/divingserver
        - jake build
        - docker build -t $DOCKER_USERNAME/$DOCKER_REPO .

      before_deploy:
        - cd $TRAVIS_BUILD_DIR
        - openssl aes-256-cbc -K $encrypted_7e0ade2cd31e_key -iv $encrypted_7e0ade2cd31e_iv
          -in mira_rsa.enc -out /tmp/deploy_rsa -d
        - openssl aes-256-cbc -K $encrypted_ed605b757ff8_key -iv $encrypted_ed605b757ff8_iv
          -in ftp_rsa.enc -out /tmp/ftp_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - chmod 600 /tmp/ftp_rsa
        - ssh-add /tmp/deploy_rsa
        - ssh-add /tmp/ftp_rsa
        - cd $TRAVIS_BUILD_DIR
        - chmod a+x deploy_prod.sh
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      deploy:
        provider: script
        skip_cleanup: true
        script: "./deploy_prod.sh"

cache:
  yarn: true
  directories:
    - divingapp/node_modules

notifications:
  email:
    - vinnie@script4web.nl
